Try some basic deployment testing

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -7,11 +7,11 @@ on:
 env:
   ARTIFACTS: artifacts
   ARTIFACTS_CACHE: artifacts-${{ github.sha }}
+  WINDOWS_DEPLOY_CACHE: windows-deploy-${{ github.sha }}
 
 jobs:
   check-version:
     runs-on: ubuntu-latest
-    continue-on-error: true
 
     steps:
       - name: Check out code
@@ -45,7 +45,6 @@ jobs:
 
   artifacts:
     runs-on: ubuntu-latest
-    needs: [check-version]
 
     outputs:
       tag: ${{ steps.gitploy.outputs.tag }}
@@ -102,7 +101,7 @@ jobs:
 
   draft:
     runs-on: ubuntu-latest
-    needs: [artifacts]
+    needs: [artifacts, check-version]
 
     env:
       TAG: ${{ needs.artifacts.outputs.tag }}
@@ -128,6 +127,74 @@ jobs:
           files: |
             ${{ env.ARTIFACTS }}/deploy_shapeflow-${{ needs.artifacts.outputs.tag }}.py
             ${{ env.ARTIFACTS }}/dist-${{ needs.artifacts.outputs.tag }}.tar.gz
+
+  test-deploy:
+    needs: [artifacts, draft]
+    continue-on-error: true  # todo: temporary
+
+    strategy:
+      matrix:
+        include:
+          - os: ubuntu-latest
+            python-version: 3.7
+          - os: ubuntu-latest
+            python-version: 3.8
+          - os: windows-latest
+            python-version: 3.8
+
+    runs-on: ${{ matrix.os }}
+
+    env:
+      TAG: ${{ needs.artifacts.outputs.tag }}
+
+    steps:
+      - name: Set up Python
+        uses: actions/setup-python@v2
+        with:
+          python-version: ${{ matrix.python-version }}
+
+      - name: Cache dev directory
+        if: ${{ startsWith(matrix.os, 'windows') }}
+        uses: actions/cache@v2
+        with:
+          path: .
+          key: ${{ env.WINDOWS_DEPLOY_CACHE }}
+
+      - name: Download deployment script
+        run: wget https://github.com/ybnd/shapeflow/releases/download/$TAG/deploy_shapeflow-$TAG.py
+
+      - name: Run deployment script
+        run: python deploy_shapeflow-$TAG.py  # todo: will fail because of y/n prompt
+
+      - name: Should set up development environment
+        run: tree .
+
+      - name: Should run sf.py
+        run: |
+          python sf.py --version
+          python sf.py --background &disown
+          sleep 10
+
+
+  test-cairo-setup:
+    runs-on: windows-latest
+    needs: test-deploy
+
+    steps:
+      - name: Cache dev directory
+        if: ${{ startsWith(matrix.os, 'windows') }}
+        uses: actions/cache@v2
+        with:
+          path: .
+          key: ${{ env.WINDOWS_DEPLOY_CACHE }}
+      - name: Should fail to import cairocffi
+        run: .venv\Scripts\python -c "import cairocffi" || true
+      - name: Setup cairo
+        run: pyton sf.py setup-cairo
+      - name: Should successfully import cairocffi
+        run: .venv\Scripts\python -c "import cairocffi"
+
+
 
 
 
